### PR TITLE
Social graphics

### PR DESCRIPTION
**Pull request by Shrinks99**
Includes a new profile photo as well as the YouTube channel art background and YouTube video thumbnail.

### CODE REVIEW

**Comment by Shrinks99** [comment]
Don't merge this just yet, the thumbnail needs to be updated as the date is covered by the video length indicator on YouTube.

**Comment by Shrinks99** [comment]
Okay this branch is ready.

**Comment by dcwalk** [comment]
What is the difference between social-graphics and youtube/thumbnail?

**Comment by dcwalk** [comment]
screen shot 2018-08-17 at 2 54 02 pm

Also seeing some artifacts on this for the social media links (but is that beyond our control? maybe just my screen)

Finally, I thought we were using the same things that we used for twitter on youtube? The square on rectangle looks a little odd to my eyes

**Comment by Shrinks99** [comment]
Unfortunately (much to my chagrin) there is nothing that can be done about the compression artefacts.  This image was uploaded as a PNG.

The OurNetworks button graphic used on twitter is a circular transparent PNG and YouTube just makes a white box around it for the profile photo.  I agree it looks rather odd with the drop shadow and for the new one I'm open to colour choices / a black and white colour scheme.

screen shot 2018-08-17 at 5 02 40 pm

The other thing about profile pictures is that the image also has to be capable of scaling to vastly different sizes while still remaining a recognizable graphic.  The real downside of the current graphic (which IS great for buttons as I believe it was intended for) is that some of the text is not visible at smaller scales when the image is beside a Tweet for example.
smallprofilepic
Twitter makes these images a mere 48x48 pixels large!  YouTube has the same sizing for profile pictures in the comment section.  In an attempt to make this piece of branding clearer I created the simplified logomark profile photo included in this PR.

**Review by dcwalk — APPROVED** [review]
I regigged the folder structure to remove a space in foldername and mirror how we use source in other dirs. Sorry for the long delay, looks good!

**Pull request merged**
