### PR TITLE
Livestream AI Files

### PR DESCRIPTION
**Pull request by Shrinks99**
Adds the AI project files for the livestream graphics.  Also includes the referenced sponsor logos.

Exported graphics and the OBS .json will go over in [ournetworks/2018/tree/master/livestream](https://github.com/ournetworks/2018/tree/master/livestream) once I get the .json from @ASoTNetworks who will send them to me on Friday.

### CODE REVIEW

**Review by garrying — COMMENTED** [review]
@Shrinks99 Thanks for following up! I think the folder could be `live-stream` (minus `graphics`). Also, maybe we could have the `.ai` files in a source folder, and PNG exports at the top-level.

**Comment by Shrinks99** [comment]
I will rename the folder and put the AI files in a 'source' folder.  While I understand wanting to have rasterized graphics on here I would argue that the PNG files should go along with the JSON as they are required to actually use the scenes in OBS.  If we're cool with having those files also mirrored and existing in both places I will also include them here.  Up to you all!

**Comment by dcwalk** [comment]
I'm inclined for us just to put these all into 2018 then? I mean we have the posters there.
I'm feeling mostly unsure about adding all the sponsor logos to this repo 🤷‍♀️ but also agree with @garrying 's restructure thoughts regardless of where it lands

**Comment by Shrinks99** [comment]
@garrying and I discussed embedded vs linked sponsor logos, the files are currently linked which we agreed can be kept for now.  The PNGs will be mirrored in the livestream directory along with the JSON file.

**Pull request merged**
