### PR TITLE
2018 Pins

### PR DESCRIPTION
**Pull request by garrying**
- 8.5x11 sheets
  - Ideally, they should be printed at actual size
- 1.25-inch pins are `our-networks-pins-design-X-125.pdf`
- 1-inch pins are `our-networks-pins-design-X-1.pdf`

### CODE REVIEW

**Comment by dcwalk** [comment]
I think this looks good -- I feel like this is a really basic question so forgive me: but there is a bleed that brings the buttons directly up against each other, correct? so using a paper cutter into strips means I have a bit of leeway if I'm not totally straight on the cuts.

**Review by dcwalk — APPROVED** [review]
looks good!

**Comment by garrying** [comment]
Yeah there's a 0.16-inch bleed around 1-inch pin, and 0.2-inch bleed on the 1.25-inch pin.

Also, I messed up the PDF exporting; redid the PR commit with dd33719 for the print-ready files.

**Comment by dcwalk** [comment]
Okay look great! I'm ready to merge if you are, one thing -- 
eventually would be nice to move your WIP images over here and imbed them in 2018/README.md as an overview of all the siick looks :)

**Pull request merged**
