### PR TITLE
Public Program Digital Handbill

### PR DESCRIPTION
**Pull request by garrying**

### CODE REVIEW

**Comment by dcwalk** [comment]
Looks good, two thoughts:

1. there are extra spaces around the time em/n dash on the screening
2. I read our program as those events ending at 10 pm not 9.45
3. I wonder if we should have a snazzy name for the screening?
  RE:screening Infrastructures  (too far?)

4. Do we want to hype things more?

  - "Events free and open to the public"?
  - name the keynote: "A Digital Bundle" 
  - add descriptions, like 1 line under each?
    - "Check out copies of tech and social infrastructure zines"
    - "Hear Dr. Jennifer Wemigwans talk about Indigenous protocols and ethics and Indigenous knowledge online. Followed by two sound art (?) performances
    -  Video essays and experimental explorations of the infrastructures of our contemporary digital communications.

**Review by dcwalk — CHANGES_REQUESTED** [review]
See comment

**Comment by garrying** [comment]
I think adding descriptions is good. Is there a way of shortening the descriptions of the keynote/kickoff and screening to match the length of the zine description?

our-networks-post-ups-handbill

**Comment by dcwalk** [comment]
Ohhhh noooo my comment got eaten :(

I'll try to recreate here...

Zine Library
Check out copies of tech and social infrastructure zines

"A Digital Bundle" Keynote
Dr. Jennifer Wemigwans relates Indigenous protocols and ethics to a networked world 

Outdoor screening
Experimental video essays exploring the infrastructures of our contemporary digital communications

(this imagines dropping kickoff mention and having that just on the program)

**Comment by garrying** [comment]
Updated:
our-networks-post-ups-digital-handbill-public-program

**Comment by benhylau** [comment]
Now it reads like a 3.5 hour keynote :)
but okay with this

**Review by benhylau — APPROVED** [review]

**Review by dcwalk — APPROVED** [review]

**Pull request merged**
