### PR TITLE
2019 Stickers, Buttons, and Post-ups

### LINKED ISSUE #56: Printed Post Up Designs
This list was copied over from 2018:
- [x] Final content
- [x] 8.5x11 post ups (Black/White)
- [x] 8.5x5.5 post ups (Black/White)
- [x] 5.5x4.25 post ups (Black/White)
- [x] 11x17 post ups (stretch)
- [ ] A0 posters (stretch)

### LINKED ISSUE #68: Create 2019 Stickers and Buttons
## Buttons
- 1 inch
- 1.25 inch

## Stickers
- Square: 2 inch x 2 inch
- Circle: 2 inch
- Rectangle: 2.25 inch x 1 inch
- Rectangle: 2 inch x 1 inch

### PR DESCRIPTION
**Pull request by garrying**
Closes https://github.com/ournetworks/2019/issues/68 and closes https://github.com/ournetworks/2019/issues/56
- [x] Buttons sheets
- [x] Stickers sheets
- [x] Post-ups (Pending Qri logo)
- [x] Initial social image

### CODE REVIEW

**Review by dcwalk — APPROVED** [review]
BUTTONS LOOK SIIIICK! :tada:

**Comment by dcwalk** [comment]
I will merge this tomorrow and aim to print some handbills to test :dancer:

**Comment by garrying** [comment]
Updated the description to note that the Qri logo is pending

**Comment by dcwalk** [comment]
@garrying -- qri logo came in, any possibility for a revision on post-ups tonightish? 
I can print tomorrow!

**Comment by garrying** [comment]
@dcwalk updated source and pdfs in f0aa2ca

**Comment by dcwalk** [comment]
Great! Much excitement! I bought some test paper, ideally will print around lunch.

**Pull request merged**
