### PR TITLE
2018 Shirts and Tote Designs

### PR DESCRIPTION
**Pull request by garrying**
Following up on https://github.com/ournetworks/2018/issues/42

- The file naming should match up to the order sheet (Let me know if it doesn't)
- The `.eps` are exports from the `source/our-networks-shirts.ai`
- Reference for art size and positioning in `our-networks_shirt-mockups.eps`
- All text has been outlined
- 2018 Tote mockup is not include (Can add if needed)

### CODE REVIEW

**Comment by dcwalk** [comment]
We've budgeted for the tote, so I think it should be included...?

**Comment by benhylau** [comment]
Is the tote design itself not the same as the 2018 shirt? I think the current quote is for same pattern.

**Review by benhylau — APPROVED** [review]

**Comment by garrying** [comment]
Yes. It's the same design as the 2018 shirt. I'll add a mockup for scale/placement (It'll be similar to the shirt) in a bit.

**Comment by dcwalk** [comment]
🎉 🌮 🎉  looks like we are good to merge? I'll do so tonight if no one else does

**Pull request merged**
