### PR TITLE
Our Networks 2019 Stream Graphics

### PR DESCRIPTION
**Pull request by Shrinks99**
Nothing officially finaled as of yet, this still uses the old TMAC logo.  Once I'm given a new vector for that I'll insert it.

"Venue Partner" has also been made singular.

### CODE REVIEW

**Comment by Shrinks99** [comment]
I've added the new sponsor logos & created a more finalized lockup for the sponsors.  I've also included an end card for the stream to be displayed at the end of each day in order to let anyone watching know that the stream has ended for the day / the conference.  In testing with Yurko & Elon  I've noticed that when there are no new video chunks the player just pulls the last good chunk and plays that.  Playing this end card for 5-10 minutes and the end of each day should result in the player showing it if people try to play the stream when we aren't live!  It's also got credits on it because hey, that's nice! :D

nostream-01-threecard

end-card

**Comment by dcwalk** [comment]
Would it be possible to use the bricks SVG or one of the other existing
treatments we already (all in the artwork repo?) have for the end stream?
Or to have to overlapping/laid figures as that treatment does originally?

I'm trying to think about the visual thread connecting this to the
conference and this last slide feels like a break from the aesthetic.

**Comment by Shrinks99** [comment]
> Would it be possible to use the bricks SVG or one of the other existing
treatments we already (all in the artwork repo?) have for the end stream?

Done!
end-card

I also have a version of the intro for the published videos ready for review: https://youtu.be/jRVOFWIWoJM

**Comment by benhylau** [comment]
In the intro video it looks like the text isn't vertically centred. Maybe:
- conference title centred
- talk title centred, presenter name below title (instead of the whole block centred)

Otherwise it looks good to me!

@dcwalk @garrying thoughts?

For the slide I think @dcwalk mentioned dropping Conference organizers, can we confirm?

**Comment by dcwalk** [comment]
Yea, to follow up, tho would favour/want @garrying to weigh in:

RE: **End Stream** graphic

To make sure I understand, will this only be played to end the stream for a set period each day, or will this be played every evening, e.g., Friday overnight until Saturday?
  - if played overnight we may want to consider the "Thanks for watching" language

My other feedback:
- Spoke with all organizers and we do not want ourselves credited on the stream graphic, we only want it on the website 
  - Do you as A/V team want the recognition on the stream graphic as well as the website? if so, I wonder how we want to handle the additional volunteers
- I wonder about playing with the size of the bricks graphic and the title, more inline with the half letter post up: https://github.com/ournetworks/artwork/blob/master/2019/post-ups/our-networks-post-ups-half-letter.pdf 
- Also, is seems like you could play with moving closer to the lineweight from the post up or the shading from the website and they might add some texture to the bricks.

RE: **Video Intro**
- Agree about moving toward centering the block but not the lines at @benhylau mentioned 
- Something feels disruptive about how the RE: Infrastructures text transformation, I wonder if it might flow better with the moving shapes if it also moved in from below? 
- That would also significantly cut down on the intro, which feels like it hangs a little to me

**Comment by garrying** [comment]
Sponsor logos:
- Scale of the Infura wordmark should be reduced (match height to adjacent white `dat://` text)

`Thanks for watching`:
-  Agree with @dcwalk on playing up the bricks. I guess the logic of how we've been displaying them is: large, sometimes cropped, and underneath large text
- "Thanks for watching" could be larger
- Could the `>` motif be incorporated in some way?

Video intro:
- Intro fly-in shapes sequence feels a bit gratuitous in length—could be simplified in the number of shapes and time it takes to get to the title build-in?
- Centered text hasn't been a thing we've done when setting `RE: Infrastructures`
- and I wonder if we could apply the same scaling logic here where we size `RE: Infrastructures` to span the width of its given container
- The slow zoom on the text effect seems a little distracting
- In keeping to our text setting logic: session titles/name are left aligned, large, narrow line-height
- Would it make sense to bold presents' names?
- Also let's check back on https://github.com/ournetworks/2019/issues/96#issuecomment-524132548 on whether text order/size/weights makes sense moving between intro to lower third

**Comment by Shrinks99** [comment]
I've done my best to address the feedback!  Here are the new updates:

**End Card**
end-card
"Thanks for watching" has been made larger, the stroke on the bricks has been increased and the conference organizers have been removed.  If we want to add AV volunteer credits this can be done per-day and I can give Elon a new png.  This would go in the middle column (currently removed but see above for an example).  @dcwalk: This will be played once per-day at the end of the day for about 10 minutes or so as a nice little sign-off to let people know the stream is over.

This graphic can *also* be re-purposed as an [end screen](https://support.google.com/youtube/answer/6388789?hl=en) for the YouTube upload should we want that (could be nice!  Those tend to increase viewership if you're into playing the YouTube game at all :P )

EDIT:  Apparently I've misinterpreted the note on the bricks.  Will revise in a new version.

**Between Talks**
nostream-01-threecard
Infura logo made smaller, good call @garrying!

**Video Intro**
https://youtu.be/-Jl4uOgsEk8
I think tightening this up a bit is also a good call, I've shortened the start by 40 frames.  The text has been moved and combined with the talk title which allows for both to be on-screen longer.

Some things to note: 
1. Because both the talk and presenter names are featured in the beginning of the video I will not have lower thirds present until the very end.
2. The same type treatment given to the conference title *can* be added to the presenter & talk name however this will add overhead for me.  Having them fade in like this will cut down on the amount of exporting and files that need to be created (just one frame sequence in After Effects VS one sequence for every talk).  At the end of the day I'm cool with doing that for all the talks but know that it will take longer.

**Comment by Shrinks99** [comment]
The end card has been updated, I've attempted to match better to the existing layouts of the bricks.

end-card

**Comment by dcwalk** [comment]
@Shrinks99 I wonder if it could look more like this on the handbill?

So: 
- lighter stroke /line weight on the bricks in proportion with the title (feel heavy/clunky)
- more of the bricks on the graphic (its a little visually confusing as to what it actually is with this much of the image outside of the frame)

Screenshot_2019-09-13_11-43-38

**Comment by Shrinks99** [comment]
Here's an updated version of the end card that should hit the notes!

end-card
(Includes fix from the commit below)

**Comment by Shrinks99** [comment]
There has been some discussion about giving the Internet Society a thumbnail to use if they are to re-stream Our Networks on their Vimeo channel, that aside it seems the thumbnail should addressed sooner rather than later anyways so lets start that now!

This was last year's thumbnail graphic...
aether

I've never been incredibly happy with it.  On the [Our Networks videos page](https://2018.ournetworks.ca/conference/recorded-talks/) including the talk title is redundant and on [YouTube](https://www.youtube.com/channel/UCudGRFTjVGsrKF0h27GER2g/videos) the title text is small and the same redundancy of information issue exists.  Including the title on the graphic also means that we need to be able to either shorten titles or just _even_ smaller type for long talk titles.  Ideally thumbnail images are engaging in some way and the bottom line is that I don't think our current system is all that great.

I would like to keep the year and conference title in the thumbnail to give people an easy way of differentiating content per-year, any suggestions as to what should be done with the rest of the graphic?  Presenter headshots have been done before by other talks? (presumably if presenters are having their talks recorded they'd be cool with a headshot?)  Different retro web clip art with a relation to the talk information?  Presenter names?

**Comment by Shrinks99** [comment]
Updated with new Temporal logo:
nostream-01-threecard

**Review by dcwalk — COMMENTED** [review]
Gonna merge this because we're post event!

**Pull request merged**
